package model;

public enum Clothes {
    SUIT_SHIRTS("SUIT SHIRTS", "CAMISAS DE TRAJE"),
    TIES("TIES", "CORBATAS"),
    DRESS("DRESS", "VESTIDO"),
    BLOUSE("BLOUSE", "BLUSA"),
    SOCK("SOCK", "CALCETÍN"),
    SOCKS("SOCKS", "CALCATINES"),
    SKIRT("SKIRT", "FALDA"),
    CROPPED_TANK_TOP("CROPPED TANK TOP", "TOP SIN MANGAS RECORTADA"),
    TOP("TOP", "TOP"),
    COAT("COAT", "ABRIGO"),
    JACKET("JACKET", "CHAQUETA"),
    T_SHIRT("T SHIRT", "CAMISA"),
    TROUSERS("TROUSERS", "PANTALONES"),
    TROUSER("TROUSE", "PANTALON"),
    PANTS("PANTS", "PANTALONES"),
    JEANS("JEANS", "PANTALONES VAQUEROS"),
    JEANS_SHORTS("JEANS SHORTS", "JEANS CORTOS"),
    PULLOVER("PULLOVER", "JERSEY"),
    SWEATER("SWEATER", "SUÉTER"),
    JUMPERS("JUMPERS", "JUMPERS"),
    JUMPER("JUMPER", "JUMPER"),
    HAT("HAT", "SOMBRERO"),
    SUNGLASSES("SUNGLASSES", "LENTES"),
    HOOD("HOOD", "CAPUCHA"),
    SWEATSHIRT("SWEATSHIRT", "CAMISA DE ENTRENAMIENTO"),
    SWEATSHIRTS("SWEATSHIRTS", "SUDADERAS"),
    GLOVES("GLOVES", "GUANTES"),
    MITTEN("MITTEN", "MITÓN"),
    MITTENS("MITTENS", "MITONES"),
    DIAPPER("DIAPPER", "PAÑAL"),
    ROMPER_SUIT("ROMPER SUIT", "TRAJE DE MAMELUCO"),
    SANDALS("SANDALS", "SANDALIAS"),
    NAPPY("NAPPY", "PAÑAL"),
    BIKINI("BIKINI", "BIKINI"),
    BRA("BRA", "SOSTÉN"),
    G_String("G STRING", "TANGA"),
    SWIMMING_TRUNKS("SWIMMING TRUNKS", "SHORTS DE BAÑO"),
    SWIMMING_COSTUME("SWIMMING COSTUME", "SWIMMING COSTUME"),
    NIGTH_DRESS("NIGTH DRESS", "VESTIDO DE NOCHE"),
    BATHING_COSTUME("BATHING COSTUME", "TRAJE DE BAÑO"),
    PYJAMA("PYJAMA", "PIJAMA"),
    DRESSING_GOWN("DRESSING GOWN", "BATA"),
    NIGHT_TIE("NIGHT TIE", "LAZO DE NOCHE"),
    UNDERWEAR("UNDERWEAR", "ROPA INTERIOR"),
    WOOLEN_HAT("WOOLEN HAT", "SOMBRERO DE LANA"),
    BOXER("BOXER", "BOXER"),
    BOXER_SHORTS("BOXER SHORTS", "BOXERS"),
    BOBBLE_HAT("BOBBLE HAT", "SOMBRERO CON BOBO"),
    KNICKERS("KNICKERS", "BRAGAS"),
    SHOES("SHOES", "TENIS"),
    SHOE("SHOE", "ZAPATO"),
    BOOTS("BOOTS", "BOTAS"),
    STOCKING_TIGHTS("STOCKING TIGHTS", "MEDIAS DE MEDIAS"),
    STOCKING("STOCKING", "MEDIA"),
    VEST("VEST", "CHALECO"),
    LADIE_SHOES("LADIE SHOES", "ZAPATOS DE MUJERES"),
    WELLINGTONS("WELLINGTONS", "BOTAS DE GOMA"),
    SNEAKERS("SNEAKERS", "ZAPATILLAS/TENIS DEPORTIVOS"),
    SLIPPERS("SLIPPERS", "ZAPATILLAS"),
    BERET("BERET", "BERET"),
    BOWLER_HAT("BOWLER HAT", "BOWLER HAT"),
    KNITTED_HAT("KNITTED HAT", "SOMBRERO TEJIDO"),
    CAP("CAP", "GORRA");

    private final String clothes;
    private final String clothesSpTranslation;

    private Clothes(String clothes, String clothesSpTranslation) {
        this.clothes = clothes;
        this.clothesSpTranslation = clothesSpTranslation;
    }

    public String getClothes() {
        return clothes;
    }
    
     public String getClothesSpTrns() {
        return clothesSpTranslation;
    }
}
